Vagrant.configure(2) do |config|
  config.vm.define "swarmmanager" do |swarmmanager|
    swarmmanager.vm.box = "ubuntu/trusty64"
    swarmmanager.vm.network "private_network", ip: "192.168.0.248"
    swarmmanager.vm.hostname = "swarmmanager.example.com"
    #swarmmanager.vm.provision "shell", path: "docker-swarm/docker_install.sh"
	swarmmanager.vm.provision "shell", path: "docker_install.sh"
  end
  config.vm.define "swarmagent1" do |swarmagent1|
    swarmagent1.vm.box = "ubuntu/trusty64"
    swarmagent1.vm.network "private_network", ip: "192.168.0.247"
    swarmagent1.vm.hostname = "docker-swarmagent1.example.com"
    swarmagent1.vm.provision "shell", path: "docker_install.sh"
  end
  config.vm.define "swarmagent2" do |swarmagent2|
    swarmagent2.vm.box = "ubuntu/trusty64"
    swarmagent2.vm.network "private_network", ip: "192.168.0.246"
    swarmagent2.vm.hostname = "docker-swarmagent2.example.com"
    swarmagent2.vm.provision "shell", path: "docker_install.sh"
  end
end
